#!/data/data/com.termux/files/usr/bin/env python
import ast
import importlib
import inspect
import os
import site
import sys
import zipfile
from multiprocess import Pool
from pathlib import Path
from collections import deque
from textwrap import dedent
from loguru import logger

from dh import get_files, unique_path

BASE_DIR = Path("/sdcard/doc")
importables = [
    "__future__",
    "_aix_support",
    "_collections_abc",
    "_compat_pickle",
    "_compression",
    "_markupbase",
    "_osx_support",
    "_py_abc",
    "_pydatetime",
    "_pydecimal",
    "_pyio",
    "_pylong",
    "_sitebuiltins",
    "_strptime",
    "_sysconfigdata__linux_",
    "_threading_local",
    "_weakrefset",
    "abc",
    "aifc",
    "antigravity",
    "argparse",
    "ast",
    "asyncio",
    "base64",
    "bdb",
    "bisect",
    "bz2",
    "cProfile",
    "calendar",
    "cgi",
    "cgitb",
    "chunk",
    "cmd",
    "code",
    "codecs",
    "codeop",
    "collections",
    "colorsys",
    "compileall",
    "concurrent",
    "configparser",
    "contextlib",
    "contextvars",
    "copy",
    "copyreg",
    "crypt",
    "csv",
    "ctypes",
    "curses",
    "dataclasses",
    "datetime",
    "dbm",
    "debpython",
    "decimal",
    "difflib",
    "dis",
    "doctest",
    "email",
    "encodings",
    "ensurepip",
    "enum",
    "filecmp",
    "fileinput",
    "fnmatch",
    "fractions",
    "ftplib",
    "functools",
    "genericpath",
    "getopt",
    "getpass",
    "gettext",
    "glob",
    "graphlib",
    "gzip",
    "hashlib",
    "heapq",
    "hmac",
    "html",
    "http",
    "idlelib",
    "imaplib",
    "imghdr",
    "importlib",
    "inspect",
    "io",
    "ipaddress",
    "json",
    "keyword",
    "lib2to3",
    "linecache",
    "locale",
    "logging",
    "lzma",
    "mailbox",
    "mailcap",
    "mimetypes",
    "modulefinder",
    "multiprocessing",
    "netrc",
    "nntplib",
    "ntpath",
    "nturl2path",
    "numbers",
    "opcode",
    "operator",
    "optparse",
    "os",
    "pathlib",
    "pdb",
    "pickle",
    "pickletools",
    "pipes",
    "pkgutil",
    "platform",
    "plistlib",
    "poplib",
    "posixpath",
    "pprint",
    "profile",
    "pstats",
    "pty",
    "py_compile",
    "pyclbr",
    "pydoc",
    "pydoc_data",
    "queue",
    "quopri",
    "random",
    "re",
    "reprlib",
    "rlcompleter",
    "sched",
    "secrets",
    "selectors",
    "shelve",
    "shlex",
    "shutil",
    "signal",
    "site",
    "smtplib",
    "sndhdr",
    "socket",
    "socketserver",
    "sqlite3",
    "sre_compile",
    "sre_constants",
    "sre_parse",
    "ssl",
    "stat",
    "statistics",
    "string",
    "stringprep",
    "struct",
    "subprocess",
    "sunau",
    "symtable",
    "sysconfig",
    "tabnanny",
    "tarfile",
    "telnetlib",
    "tempfile",
    "textwrap",
    "threading",
    "timeit",
    "tkinter",
    "token",
    "tokenize",
    "tomllib",
    "trace",
    "traceback",
    "tracemalloc",
    "tty",
    "turtle",
    "turtledemo",
    "types",
    "typing",
    "unittest",
    "urllib",
    "uu",
    "uuid",
    "venv",
    "warnings",
    "wave",
    "weakref",
    "webbrowser",
    "wsgiref",
    "xdrlib",
    "xml",
    "xmlrpc",
    "zipapp",
    "zipfile",
    "zipimport",
    "zoneinfo",
    "_asyncio",
    "_bisect",
    "_blake2",
    "_bz2",
    "_codecs_cn",
    "_codecs_hk",
    "_codecs_iso2022",
    "_codecs_jp",
    "_codecs_kr",
    "_codecs_tw",
    "_contextvars",
    "_crypt",
    "_csv",
    "_ctypes",
    "_ctypes_test",
    "_curses",
    "_curses_panel",
    "_datetime",
    "_dbm",
    "_decimal",
    "_elementtree",
    "_gdbm",
    "_hashlib",
    "_heapq",
    "_json",
    "_lsprof",
    "_lzma",
    "_md5",
    "_multibytecodec",
    "_multiprocessing",
    "_opcode",
    "_pickle",
    "_posixshmem",
    "_posixsubprocess",
    "_queue",
    "_random",
    "_sha1",
    "_sha2",
    "_sha3",
    "_socket",
    "_sqlite3",
    "_ssl",
    "_statistics",
    "_struct",
    "_testbuffer",
    "_testcapi",
    "_testclinic",
    "_testimportmultiple",
    "_testinternalcapi",
    "_testmultiphase",
    "_testsinglephase",
    "_xxinterpchannels",
    "_xxsubinterpreters",
    "_xxtestfuzz",
    "_zoneinfo",
    "array",
    "audioop",
    "binascii",
    "cmath",
    "fcntl",
    "grp",
    "math",
    "mmap",
    "ossaudiodev",
    "pyexpat",
    "readline",
    "resource",
    "select",
    "syslog",
    "termios",
    "unicodedata",
    "xxlimited",
    "xxlimited_35",
    "xxsubtype",
    "zlib",
    "z3",
    "Crypto",
    "Cryptodome",
    "Cython",
    "GPUtil",
    "IPython",
    "InquirerPy",
    "MeCab",
    "OleFileIO_PL",
    "OpenSSL",
    "PIL",
    "PyPDF2",
    "RestrictedPython",
    "Xlib",
    "_MeCab",
    "_argon2_cffi_bindings",
    "_black_version",
    "_brotli",
    "_cffi_backend",
    "_distutils_hack",
    "_hypothesis_ftz_detector",
    "_hypothesis_globals",
    "_hypothesis_pytestplugin",
    "_multiprocess",
    "_pillow_heif",
    "_pytest",
    "_rcssmin",
    "_rjsmin",
    "_ruamel_yaml",
    "_scikit_learn_editable_loader",
    "_sounddevice",
    "_soundfile",
    "_uniout",
    "_yaml",
    "a11y_pygments",
    "absl",
    "agentmail",
    "ahs_compressor",
    "aiodns",
    "aiofiles",
    "aiohappyeyeballs",
    "aiohttp",
    "aiohttp_jinja2",
    "aioresponses",
    "aiosignal",
    "aiosqlite",
    "alabaster",
    "altair",
    "altair_tiles",
    "amqp",
    "androidhelper",
    "annotated_doc",
    "annotated_types",
    "anyascii",
    "anyio",
    "anywidget",
    "appdirs",
    "appnope",
    "arabic_reshaper",
    "argcomplete",
    "argon2",
    "arithmetic_compressor",
    "arrow",
    "ascii_magic",
    "asgiref",
    "asn1crypto",
    "aspose_compressor",
    "astor",
    "astpretty",
    "astroid",
    "asttokens",
    "astunparse",
    "async_lru",
    "async_timeout",
    "atomicwriter",
    "attr",
    "attrs",
    "auditwheel",
    "authencoding",
    "authlib",
    "autoapi",
    "autocommand",
    "autodoc2",
    "autodocsumm",
    "autoflake",
    "autoimport",
    "automat",
    "autopep8",
    "babel",
    "backcall",
    "backoff",
    "backports",
    "backrefs",
    "baidubce",
    "baler_compressor",
    "bandit",
    "bcj",
    "bcrypt",
    "bearer",
    "beartype",
    "bidi",
    "bidict",
    "billiard",
    "binaryornot",
    "black",
    "blackboxprotobuf",
    "blackd",
    "blade",
    "blake3",
    "bleach",
    "blessed",
    "blib2to3",
    "blinker",
    "blis",
    "blosc",
    "blurb",
    "boolean",
    "breathe",
    "brotli",
    "brotlicffi",
    "bs4",
    "bson",
    "bubus",
    "build",
    "bumpversion",
    "cachecontrol",
    "cachelib",
    "cachetools",
    "cairocffi",
    "cairosvg",
    "catalogue",
    "cattr",
    "cattrs",
    "cbor2",
    "cchardet",
    "cdp_use",
    "celery",
    "cellfolding",
    "certifi",
    "cffi",
    "cftime",
    "chardet",
    "charset_normalizer",
    "check_sdist",
    "classes",
    "claude_json2md",
    "cleo",
    "cli",
    "click",
    "click_default_group",
    "click_didyoumean",
    "click_log",
    "click_plugins",
    "click_repl",
    "cloudpathlib",
    "cloudpickle",
    "cmake",
    "cmapfile",
    "codeslim",
    "codespell_lib",
    "colorama",
    "coloredlogs",
    "colorlog",
    "colorzero",
    "comm",
    "component",
    "compression_prompt",
    "compresslib",
    "condense_json",
    "confection",
    "configupdater",
    "cons",
    "constantly",
    "construct",
    "context_compressor",
    "contourpy",
    "convertdate",
    "cookiecutter",
    "courlan",
    "coverage",
    "coveralls",
    "cppbktree",
    "cppy",
    "cpuinfo",
    "crashtest",
    "crccheck",
    "crosshair",
    "cryptography",
    "cssbeautifier",
    "cssselect",
    "cssselect2",
    "cssutils",
    "ctypesgen",
    "curl",
    "cv2",
    "cy_heu",
    "cycler",
    "cython",
    "cytoolz",
    "daglint",
    "dateparser",
    "dateparser_cli",
    "dateparser_data",
    "dateparser_scripts",
    "dateutil",
    "dbus",
    "deadcode",
    "debugpy",
    "decorator",
    "deep_translator",
    "deferredimport",
    "defusedxml",
    "dependency",
    "dependency_groups",
    "deprecated",
    "dicttools",
    "dill",
    "diskcache",
    "dissolve",
    "distlib",
    "distorm3",
    "distro",
    "djcall",
    "djcall_example",
    "dns",
    "dnslib",
    "docstring_parser",
    "docutils",
    "docx",
    "doit",
    "domain",
    "dotenv",
    "dry_attr",
    "dulwich",
    "dynamic_range_compression",
    "editor",
    "editorconfig",
    "einops",
    "elftools",
    "emoji",
    "emplace",
    "encutils",
    "erfa",
    "et_xmlfile",
    "etuples",
    "eval_type_backport",
    "event",
    "eventlet",
    "execnet",
    "executing",
    "fake_useragent",
    "fastapi",
    "fastapi_poe",
    "fastcrypter",
    "fastjsonschema",
    "fastrlock",
    "fasttext",
    "fastwalk",
    "fclist",
    "feedparser",
    "ffmpeg",
    "fftw",
    "fhash",
    "filelock",
    "filetype",
    "findpython",
    "fire",
    "flake8",
    "flake8_colors",
    "flake8_isort",
    "flashtext",
    "flask",
    "flask_compressor",
    "flatbuffers",
    "folder_hash",
    "fontTools",
    "fpath",
    "fpdf",
    "fqdn",
    "freetype",
    "frozendict",
    "frozenlist",
    "fsspec",
    "ftfy",
    "furo",
    "future",
    "fuzzysearch",
    "fuzzytail",
    "fuzzywuzzy",
    "gast",
    "gears",
    "gears_uglifyjs",
    "genson",
    "ghostscript",
    "ghp_import",
    "git",
    "gitdb",
    "github",
    "glob2",
    "graphviz",
    "greenlet",
    "gridfs",
    "griffe",
    "griffecli",
    "groq",
    "grpc",
    "gyp",
    "h11",
    "h2",
    "h5netcdf",
    "h5py",
    "halo",
    "hatch_vcs",
    "hatching",
    "hatchling",
    "hidapi",
    "highwayhash",
    "hijridate",
    "hookable",
    "hpack",
    "html2md",
    "html2text",
    "html_to_markdown",
    "htmldate",
    "htmlmin",
    "http_response",
    "httpcore",
    "httpie",
    "httplib2",
    "httpsig_cffi",
    "httpx",
    "httpx_sse",
    "huggingface_hub",
    "humanfriendly",
    "humanize",
    "hyperframe",
    "hyperlink",
    "hypothesis",
    "i18nmessageid",
    "id",
    "identify",
    "idna",
    "ifaddr",
    "imagecompressor",
    "imageio",
    "imageio_ffmpeg",
    "imagesize",
    "imgcat",
    "importlib_metadata",
    "importlib_resources",
    "imread",
    "incremental",
    "inflate64",
    "inflect",
    "infrastructure",
    "iniconfig",
    "inngest",
    "installer",
    "interface",
    "intersphinx_registry",
    "invoke",
    "ipdb",
    "ipwhois",
    "ipykernel",
    "ipykernel_launcher",
    "ipython_genutils",
    "ipython_pygments_lexers",
    "ipywidgets",
    "isoduration",
    "isort",
    "itsdangerous",
    "izulu",
    "jcs",
    "jedi",
    "jeepney",
    "jellyfish",
    "jenkins_cffi",
    "jinja2",
    "jinxed",
    "jiter",
    "jmespath",
    "joblib",
    "jose",
    "jpegtran",
    "jsbeautifier",
    "json5",
    "json_lines",
    "json_log_plots",
    "json_prettifier",
    "jsonlines",
    "jsonpatch",
    "jsonpointer",
    "jsonschema",
    "jsonschema_specifications",
    "jupyter-js-widgets-nbextension",
    "jupyter",
    "jupyter_cache",
    "jupyter_client",
    "jupyter_console",
    "jupyter_contrib_core",
    "jupyter_core",
    "jupyter_events",
    "jupyter_highlight_selected_word",
    "jupyter_lsp",
    "jupyter_nbextensions_configurator",
    "jupyter_server",
    "jupyter_server_terminals",
    "jupyterlab",
    "jupyterlab_jupytext",
    "jupyterlab_pygments",
    "jupyterlab_server",
    "jupyterlab_widgets",
    "jupyterlite_core",
    "jupyterlite_pyodide_kernel",
    "jupyterlite_sphinx",
    "jupyterpip",
    "jupytext",
    "jupytext_config",
    "justext",
    "jwt",
    "kaitaistruct",
    "kanren",
    "keep",
    "keyboard",
    "keyring",
    "kfreader",
    "kiwisolver",
    "kombu",
    "langdetect",
    "lark",
    "laspy",
    "latex_envs",
    "latexcodec",
    "lazy_loader",
    "lazy_object_proxy",
    "lazyloader",
    "libcst",
    "libfuturize",
    "libpasteurize",
    "libqrencode",
    "librosa",
    "license_expression",
    "linkify_it",
    "litl",
    "llm_text_compressor",
    "log_symbols",
    "loguru",
    "loky",
    "lxml",
    "lxml_html_clean",
    "lz4",
    "lzma_mt",
    "lzw3",
    "maison",
    "mando",
    "markdown",
    "markdown2",
    "markdown_it",
    "markdownify",
    "markitdown",
    "markupsafe",
    "marshmallow",
    "matplotlib",
    "matplotlib_inline",
    "maturin",
    "mccabe",
    "mcp",
    "md2ipynb",
    "mdit_py_plugins",
    "mdurl",
    "mercantile",
    "mergedeep",
    "mesonbuild",
    "mesonpy",
    "mike",
    "mistralai",
    "mistralai_azure",
    "mistralai_gcp",
    "mistune",
    "ml_dtypes",
    "mock",
    "more_itertools",
    "moviepy",
    "mpmath",
    "msgpack",
    "msgspec",
    "multidict",
    "multipart",
    "multipledispatch",
    "multiprocess",
    "multivolumefile",
    "murmurhash",
    "mypy",
    "mypy_extensions",
    "mypyc",
    "myst_parser",
    "nacl",
    "nanoid",
    "narwhals",
    "natsort",
    "nbclient",
    "nbconvert",
    "nbconvert_utils",
    "nbdev_template",
    "nbformat",
    "neovim",
    "netCDF4",
    "networkx",
    "nh3",
    "ninja",
    "nltk",
    "nose",
    "notebook",
    "notebook_shim",
    "notfound",
    "nox",
    "numpy",
    "numpydoc",
    "oauthlib",
    "oiffile",
    "olefile",
    "openai",
    "opencv_extra",
    "openpyxl",
    "opt_einsum",
    "ordlookup",
    "orjson",
    "outcome",
    "packaging",
    "pacmap",
    "paginate",
    "pallets_sphinx_themes",
    "pandocfilters",
    "parsel",
    "parso",
    "past",
    "pathspec",
    "pathvalidate",
    "patiencediff",
    "patoolib",
    "pbs_installer",
    "pcpp",
    "pdfkit",
    "pdfminer",
    "pdfplumber",
    "pdoc",
    "pefile",
    "perprint",
    "persistent",
    "peutils",
    "pexpect",
    "pfzy",
    "pickley",
    "piexif",
    "pillow_heif",
    "pip",
    "pip_check",
    "piptools",
    "pkgconfig",
    "pkginfo",
    "platformdirs",
    "pluggy",
    "ply",
    "plyer",
    "plyr",
    "pmagic",
    "png",
    "pngquant",
    "pooch",
    "portalocker",
    "portend",
    "ppdeep",
    "ppmd",
    "pre_commit",
    "premailer",
    "prettytable",
    "proglog",
    "progressbar",
    "prometheus_client",
    "prompt_toolkit",
    "propcache",
    "protego",
    "proto",
    "psutil",
    "psygnal",
    "ptr",
    "ptyprocess",
    "publicsuffix2",
    "pure_eval",
    "puremagic",
    "py",
    "py7zr",
    "pyasn1",
    "pyasn1_modules",
    "pybind11",
    "pybtex",
    "pybtex_docutils",
    "pycares",
    "pycld2",
    "pyclipper",
    "pycocotools",
    "pycodestyle",
    "pycparser",
    "pycurl",
    "pydantic",
    "pydantic_core",
    "pydantic_settings",
    "pydata_sphinx_theme",
    "pydeck",
    "pydispatch",
    "pydocstyle",
    "pydyf",
    "pyee",
    "pyflakes",
    "pygments",
    "pygments_styles",
    "pyhuff",
    "pyleri",
    "pylint",
    "pylz78",
    "pymarc",
    "pymdownx",
    "pymeeus",
    "pymongo",
    "pympler",
    "pymupdf",
    "pymupdf_fonts",
    "pynput",
    "pynvim",
    "pyopt",
    "pyotp",
    "pyparsing",
    "pypdf",
    "pypdfium",
    "pypdfium2",
    "pypdfium2_raw",
    "pyperclip",
    "pyphen",
    "pyppeteer",
    "pyppmd",
    "pyproject_api",
    "pyproject_cli",
    "pyproject_hooks",
    "pyproject_metadata",
    "pyproject_toml",
    "pyprojroot",
    "pyquery",
    "pyright",
    "pyscaffold",
    "pysrt",
    "pytesseract",
    "pytest",
    "pytest_benchmark",
    "pytest_cov",
    "pytest_textual_snapshot",
    "pytest_timeout",
    "python_discovery",
    "python_multipart",
    "pythonjsonlogger",
    "pytimeparse",
    "pytokens",
    "pytorch_sphinx_theme",
    "pytz",
    "pyudev",
    "pywebcopy",
    "pywt",
    "pyximport",
    "pyxmpp2",
    "pyzipper",
    "pyzx7",
    "qrcode",
    "qsl4ahelper",
    "questionary",
    "queuelib",
    "radon",
    "rapidfuzz",
    "rcssmin",
    "rdflib",
    "readchar",
    "readme_renderer",
    "refactor_utils",
    "referencing",
    "regex",
    "reportlab",
    "requests",
    "requests_cache",
    "requests_file",
    "requests_oauthlib",
    "requests_toolbelt",
    "retry",
    "reuse",
    "rfc3986",
    "rfc3987_syntax",
    "rich",
    "rignore",
    "rjsmin",
    "roman_numerals",
    "rpds",
    "rsa",
    "ruff",
    "run-checkpy",
    "runez",
    "runflare",
    "rust_regex_python",
    "s3bz",
    "s3transfer",
    "sassutils",
    "scikit_build_core",
    "scipy",
    "scrapy",
    "screeninfo",
    "seaborn",
    "secretstorage",
    "semantic_version",
    "send2trash",
    "sentencepiece",
    "serial",
    "serial_asyncio_fast",
    "service_identity",
    "setproctitle",
    "setupmeta",
    "setuptools",
    "setuptools_git_versioning",
    "setuptools_rust",
    "setuptools_scm",
    "sgmllib",
    "sh",
    "share_button",
    "shellingham",
    "shibuya",
    "shrinkr",
    "simler",
    "simplejson",
    "simplematch",
    "six",
    "skbuild",
    "skfuzzy",
    "skimage",
    "skimage2",
    "slugify",
    "smart_open",
    "smmap",
    "snappy",
    "sniffio",
    "snowballstemmer",
    "snscrape",
    "socket_keepalive",
    "socks",
    "sockshandler",
    "sortedcontainers",
    "sounddevice",
    "soupsieve",
    "spark_parser",
    "sphinx",
    "sphinx_autodoc_typehints",
    "sphinx_basic_ng",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_markdown_builder",
    "sphinx_rtd_theme",
    "sphinx_tabs",
    "sphinx_wagtail_theme",
    "spin",
    "spinners",
    "splaytree_compression",
    "splinter",
    "sqlalchemy",
    "sqlite_zstd",
    "sqlparse",
    "srsly",
    "ssdeep",
    "sse_starlette",
    "sseclient",
    "stack_data",
    "stagehand",
    "starlette",
    "stevedore",
    "stl_compressor",
    "stringzilla",
    "svg2png",
    "svg_turtle",
    "svgfont",
    "svglib",
    "svgpathtools",
    "svgutils",
    "svgwrite",
    "syrupy",
    "tabulate",
    "taskiq",
    "taskiq_dependencies",
    "tempora",
    "tenacity",
    "termcolor",
    "terminado",
    "terminaltables",
    "terminaltables3",
    "termuxgui",
    "tests",
    "text_unidecode",
    "textblob",
    "textdistance",
    "textual",
    "textual_dev",
    "textual_serve",
    "tf_slim",
    "tifffile",
    "tiktoken",
    "tinycss2",
    "tinyhtml5",
    "tld",
    "tldextract",
    "tldp",
    "tls_client",
    "tlz",
    "tokencost",
    "tokenizers",
    "tokenoptim",
    "toml",
    "tomli",
    "tomli_w",
    "tomlkit",
    "tools",
    "toolz",
    "toposort",
    "tornado",
    "towncrier",
    "tox",
    "tqdm",
    "trafilatura",
    "traitlets",
    "transaction",
    "tree_sitter",
    "tree_sitter_bash",
    "tree_sitter_cpp",
    "tree_sitter_javascript",
    "tree_sitter_markdown",
    "tree_sitter_python",
    "tree_sitter_regex",
    "tree_sitter_rust",
    "trio",
    "trove_classifiers",
    "tweepy",
    "twine",
    "twisted",
    "typed_ast",
    "typeguard",
    "typer",
    "typeshed_client",
    "typing_extensions",
    "typing_inspect",
    "typing_inspection",
    "tzdata",
    "tzlocal",
    "uc_micro",
    "ufoLib2",
    "uharfbuzz",
    "ujson",
    "ulid",
    "undefined",
    "unfurl",
    "unidecode",
    "unification",
    "uri_template",
    "uritemplate",
    "url",
    "url_normalize",
    "urllib3",
    "usb",
    "userpath",
    "uuid_extensions",
    "uuid_utils",
    "uvicorn",
    "uvloop",
    "validate_pyproject",
    "versioneer",
    "verspec",
    "vhack",
    "victor_smart_kill",
    "video_compressor",
    "vine",
    "virtualenv",
    "voluptuous",
    "w3lib",
    "wand",
    "wasabi",
    "watchdog",
    "watchfiles",
    "wcwidth",
    "weasel",
    "weasyprint",
    "web_compressor",
    "webcolors",
    "webencodings",
    "webob",
    "websocket",
    "websockets",
    "webtest",
    "werkzeug",
    "wget2",
    "wheel",
    "whisper",
    "widgetsnbextension",
    "willow",
    "wrapt",
    "wsproto",
    "xattr",
    "xcbgen",
    "xdg",
    "xdis",
    "xdist",
    "xmltodict",
    "xxhash",
    "xyzservices",
    "yaml",
    "yaml_env_tag",
    "yapf",
    "yapf_third_party",
    "yarg",
    "yarl",
    "yua_compressor",
    "zeroconf",
    "zipp",
    "zippy",
    "zipwalk",
    "zmq",
    "zopfli",
    "zstandard",
    "zstd",
]


def format_markdown(module_name: str, module_doc: str, functions, classes) -> str:
    parts = [f"# Module `{module_name}`\n"]

    if module_doc:
        parts.append("## Module Doc\n")
        parts.append(module_doc + "\n")

    if functions:
        parts.append("## Functions\n")
        for name, doc in functions:
            parts.append(f"### `{name}()`\n")
            parts.append(doc + "\n")

    if classes:
        parts.append("## Classes\n")
        for name, doc in classes:
            parts.append(f"### `{name}`\n")
            parts.append(doc + "\n")

    return "\n".join(parts).strip() + "\n"


def extract_ast_docs(src: str) -> tuple[str, list, list]:
    try:
        tree = ast.parse(src)
    except Exception:
        return "", [], []

    module_doc = dedent(ast.get_docstring(tree) or "").strip()
    functions = []
    classes = []

    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            doc = ast.get_docstring(node) or ""
            doc = dedent(doc).strip()
            if doc:
                functions.append((node.name, doc))

        elif isinstance(node, ast.ClassDef):
            doc = ast.get_docstring(node) or ""
            doc = dedent(doc).strip()
            if doc:
                classes.append((node.name, doc))

    return module_doc, functions, classes


def extract_from_file(py_path: str) -> tuple[str, str, str, list, list]:
    try:
        with open(py_path, encoding="utf-8") as f:
            src = f.read()
    except Exception:
        return None

    module_doc, functions, classes = extract_ast_docs(src)
    if not module_doc and not functions and not classes:
        return None

    return module_doc, functions, classes


def extract_from_importable(name: str):
    try:
        module = importlib.import_module(name)
    except Exception:
        return None

    try:
        src = inspect.getsource(module)
        return extract_ast_docs(src)
    except Exception:
        doc = dedent(inspect.getdoc(module) or "").strip()
        if not doc:
            return None
        return doc, [], []


def module_to_md_paths(name: str):
    parts = name.split(".")
    folder = os.path.join(BASE_DIR, *parts[:-1])
    filename = f"{parts[-1]}.md"
    return folder, os.path.join(folder, filename)


def file_to_md_paths(py_file: str, root: str):
    rel = os.path.relpath(py_file, root)
    parts = rel.split(os.sep)
    parts[-1] = parts[-1].replace(".py", ".md")
    folder = os.path.join(BASE_DIR, *parts[:-1])
    outfile = os.path.join(BASE_DIR, *parts)
    return folder, outfile


def save_markdown(folder: str, path: str, content: str):
    folderpath = Path(folder)
    if not folderpath.exists():
        folderpath.mkdir(exist_ok=True)
    outpath = Path(path)
    if outpath.exists():
        outpath = unique_path(outpath)
    outpath.write_text(content, encoding="utf-8")


def process_importable_task(name: str):
    logger.info(f"processing module {name}")
    result = extract_from_importable(name)
    if not result:
        return

    module_doc, functions, classes = result

    folder, out_path = module_to_md_paths(name)
    md = format_markdown(name, module_doc, functions, classes)
    save_markdown(folder, out_path, md)


def process_file_task(py_file):
    filepath = Path(py_file)
    root = str(filepath.parent)
    logger.info(f"processing file {filepath.name} from {filepath.parent.name}")
    result = extract_from_file(str(py_file))
    if not result:
        return

    module_doc, functions, classes = result
    rel = os.path.relpath(py_file)
    module_name = rel.replace(os.sep, ".").replace(".py", "")

    folder, out_path = file_to_md_paths(py_file, root)
    md = format_markdown(module_name, module_doc, functions, classes)
    save_markdown(folder, out_path, md)


def main():
    if not BASE_DIR.exists():
        BASE_DIR.mkdir(exist_ok=True)
    root_dir = Path.cwd()
    args = sys.argv[1:]
    files = [Path(arg) for arg in args] if args else get_files(root_dir, extensions=[".py", ".pyi", ".pyx"])
    logger.info("processing {len(files)} files")
    with Pool(8) as pool:
        pending = deque()
        for f in files:
            pending.append(pool.apply_async(process_file_task, (f,)))
            if len(pending) > 16:
                pending.popleft().get()
        while pending:
            pending.popleft().get()


"""
    logger.info("processing {len(importable)} importable")
    with Pool(8) as pool:
        pending=deque()
        for x in importables:
            pending.append(pool.apply_async(process_importable_task, (x,)))
            if len(pending)>16:
                pending.popleft().get()
        while pending:
            pending.popleft().get()



"""

if __name__ == "__main__":
    main()
